### ISSUE TITLE
未连接是什么意思

### ISSUE THREAD

**Issue by qaq1000w** [Mufanc/AppLock#1]
![Screenshot_2022-02-05-01-56-38-613_mufanc tools applock](https://user-images.githubusercontent.com/80654352/152579116-5f1d2f68-1633-4d66-990a-e696a8095b46.jpg)

**Comment by Mufanc** [comment]
装完模块没重启？

**Comment by qaq1000w** [comment]
> 装完模块没重启？

装完挂载了系统桌面，后面重启了两次都是显示连接失败

**Comment by qaq1000w** [comment]
失败

**Comment by qaq1000w** [comment]
解决了，关掉模块重启然后再打开再重启一次就能用了

**Comment by qaq1000w** [comment]
这个插件好像对于一些应用不能使用?刚才QQ音乐划掉不会关闭，但是ChatCraft一拉就掉后台,使用另外的那个进程锁也锁不住

**Comment by Mufanc** [comment]
报一下 MIUI 和 Android 版本，以及 Magisk 版本和你用的什么 Xposed 框架

**Comment by qaq1000w** [comment]
MIUI  12.5.4
Android  11





| |
13927539910
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月05日 20:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Mufanc/AppLock] 未连接是什么意思 (Issue #1) |

报一下 MIUI 和 Android 版本，以及 Magisk 版本和你用的什么 Xposed 框架

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qaq1000w** [comment]
| |
13927539910
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月05日 20:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Mufanc/AppLock] 未连接是什么意思 (Issue #1) |

报一下 MIUI 和 Android 版本，以及 Magisk 版本和你用的什么 Xposed 框架

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mufanc** [comment]
你在发啥？

**Comment by qaq1000w** [comment]
…邮箱回复有问题

**Comment by qaq1000w** [comment]
MIUI  12.5.4
Android  11
![Uploading Screenshot_2022-02-05-20-21-25-226_com.topjohnwu.magisk.jpg…]()
![Uploading Screenshot_2022-02-05-20-17-19-054_com.topjohnwu.magisk.jpg…]()

**Comment by Mufanc** [comment]
已经复现，模块并没有问题。这个模块的作用只是保证应用进程不被杀死，但不能阻止应用的 Activity 被销毁
