### ISSUE TITLE
最新的 2.0.1.r14.2b58fb4 显示模块未激活错误

### ISSUE THREAD

**Issue by ZZZXXX0110** [Mufanc/AppLock#3]
进入应用后 AppLock 页面显示＂模块未激活＂以及＂钩子无响应＂，如图：

![Screenshot_2022-04-04-20-45-02-279_mufanc.tools.applock.jpg](https://user-images.githubusercontent.com/37162057/161546362-0e84bb1f-4dda-44db-8c09-606aa41f32a3.jpg)

以下为设备和系统信息：

API version
93

Injection Interface
Zygisk

Framework version
1.8.0 (6482)

Manager version
1.8.0 (6482)

System version
11 (API 30)

Device
Xiaomi MiX Fold

System ABI
arm64-v8a

**Comment by ZZZXXX0110** [comment]
顺便说，我使用的是 LSPosed，稳定版更新通道的 1.8.0 版本。

**Comment by Mufanc** [comment]
我的锅，我忘了修改 proguard-rules.pro 导致在 release 中反射出现问题

**Comment by ZZZXXX0110** [comment]
> 我的锅，我忘了修改 proguard-rules.pro 导致在 release 中反射出现问题

哈哈原来如此！最新版一切正常了，非常感谢！~~~
