### ISSUE TITLE
［无法激活］lsp框架无法激活

### ISSUE THREAD

**Issue by xushet** [Mufanc/AppLock#4]
请问这个模块除了在lsp框架勾选“系统框架”和马上重启手机之外，还有什么步骤吗？![Screenshot_20220404-233814_Shady启动器.png](https://user-images.githubusercontent.com/34502902/161580966-2dd655e9-c9d7-4a30-80c1-00ad1114a9db.png)
![Screenshot_20220404-234450_Shady启动器.png](https://user-images.githubusercontent.com/34502902/161581589-41e9bf09-6b7c-4700-9a21-0003d856e813.png)
![Screenshot_20220404-234441_Shady启动器.png](https://user-images.githubusercontent.com/34502902/161581619-b6bb34f2-f3dc-4b9e-a6f8-f46d8e42cef9.png)
rom是类原生
android版本：11
lsp框架版本：1.8.0 (6489)Zygisk
magisk版本：24.3
手机型号：小米6

忘了，模块版本 2.0.1.r16.8ea45c1

**Comment by xushet** [comment]
忘了，模块版本 2.0.1.r16.8ea45c1

**Comment by Mufanc** [comment]
这个模块是针对 MIUI 官方 ROM 的，并不支持其它 ROM 澳
