### ISSUE TITLE
建议加入系统应用

### ISSUE THREAD

**Issue by 1812z** [Mufanc/AppLock#5]
部分系统应用杀的验证，想保留后台来加速启动

**Comment by Mufanc** [comment]
我该如何断句

**Comment by 1812z** [comment]
> 我该如何断句

让系统应用也能加入这个清理白名单

**Comment by Mufanc** [comment]
在 2.0.2.r22.8994610 版本中已加入相关设置，提供两种不同的应用列表获取方式以供选择
