### ISSUE TITLE
MIUI 版本显示错误（虽然并不影响使用）

### ISSUE THREAD

**Issue by ZZZXXX0110** [Mufanc/AppLock#6]
进入模块后设置页面显示 MIUI 版本为 11，但是我的 MIUI 版本是 12.5，运行的安卓 11 系统。如图

![Screenshot_2022-04-06-17-08-55-152_mufanc.tools.applock.jpg](https://user-images.githubusercontent.com/37162057/161939969-4e0ee452-bd9f-42f8-9b1c-fe93176dec95.jpg)

虽然并不影响模块使用，不过好奇怪哈哈哈

**Comment by Mufanc** [comment]
我写这玩意主要是为了判断系统是不是 MIUI，版本号随便找一个 prop 就丢上去了，下个 release 修复
