### ISSUE TITLE
希望能显示完整应用列表（现在只有图标方式和用户方式）

### ISSUE THREAD

**Issue by TOMWZT** [Mufanc/AppLock#7]
作者大大好呀
这个东西我上安卓12发现的 因为原来的进程锁不能用了
突然就找到了这个软件 这个可以用 而且还不用关闭selinux
但是这个选的应用呢 不能选没有图标的系统应用 我正好要锁的就是这样的应用 我想了一下 备份的是一个包名文件
我把应用包名直接写上去 然后恢复 软件是完全能正常工作的
但是还是希望可以在后续版本中直接勾选啦

**Comment by Mufanc** [comment]
可以加入相关选项，不过我很好奇有什么没有图标的系统应用是需要锁的😂
